apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: homely-capybara-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/homely-capybara-java-quarkus-gitops